export function getChatHTML(): string {
  const lines: string[] = [];

  lines.push('<!DOCTYPE html>');
  lines.push('<html lang="en"><head><meta charset="UTF-8">');
  lines.push('<meta name="viewport" content="width=device-width, initial-scale=1.0">');
  lines.push('<title>Azure Codex Chat</title><style>');
  lines.push('* { box-sizing: border-box; margin: 0; padding: 0; }');
  lines.push('body { font-family: var(--vscode-font-family); font-size: var(--vscode-font-size); color: var(--vscode-foreground); background: var(--vscode-sideBar-background); height: 100vh; display: flex; flex-direction: column; overflow: hidden; }');
  lines.push('#header { display: flex; align-items: center; justify-content: space-between; padding: 8px 12px; background: var(--vscode-sideBarSectionHeader-background); border-bottom: 1px solid var(--vscode-sideBarSectionHeader-border); flex-shrink: 0; }');
  lines.push('#header-title { display: flex; align-items: center; gap: 8px; font-weight: 600; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; color: var(--vscode-sideBarSectionHeader-foreground); }');
  lines.push('#header-actions { display: flex; gap: 4px; }');
  lines.push('.icon-btn { background: none; border: none; color: var(--vscode-icon-foreground); cursor: pointer; padding: 4px; border-radius: 4px; display: flex; align-items: center; opacity: 0.7; }');
  lines.push('.icon-btn:hover { opacity: 1; background: var(--vscode-toolbar-hoverBackground); }');
  lines.push('.icon-btn:disabled { opacity: 0.25; cursor: default; }');
  lines.push('.icon-btn:disabled:hover { background: none; }');
  lines.push('#context-drawer { display: none; border-bottom: 1px solid var(--vscode-panel-border); background: var(--vscode-sideBar-background); padding: 10px 12px; }');
  lines.push('#context-drawer.open { display: block; }');
  lines.push('#context-title { display: flex; align-items: center; justify-content: space-between; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; color: var(--vscode-descriptionForeground); margin-bottom: 8px; }');
  lines.push('#context-body { font-size: 12px; color: var(--vscode-foreground); display: flex; flex-direction: column; gap: 8px; }');
  lines.push('.ctx-section { padding: 8px; border: 1px solid var(--vscode-panel-border); border-radius: 6px; background: var(--vscode-textBlockQuote-background); }');
  lines.push('.ctx-row { display: flex; align-items: center; justify-content: space-between; gap: 8px; }');
  lines.push('.ctx-muted { color: var(--vscode-descriptionForeground); font-size: 11px; }');
  lines.push('.ctx-list { margin-top: 6px; display: flex; flex-direction: column; gap: 4px; }');
  lines.push('.ctx-item { display: flex; align-items: center; justify-content: space-between; gap: 8px; }');
  lines.push('.ctx-item code { background: transparent; padding: 0; }');
  lines.push('.mini-btn { background: none; border: 1px solid var(--vscode-panel-border); color: var(--vscode-button-secondaryForeground); cursor: pointer; padding: 1px 6px; border-radius: 3px; font-size: 11px; }');
  lines.push('.mini-btn:hover { background: var(--vscode-button-secondaryHoverBackground); }');
  lines.push('#messages { flex: 1; overflow-y: auto; padding: 12px 0; display: flex; flex-direction: column; gap: 2px; scroll-behavior: smooth; }');
  lines.push('#messages::-webkit-scrollbar { width: 6px; } #messages::-webkit-scrollbar-track { background: transparent; } #messages::-webkit-scrollbar-thumb { background: var(--vscode-scrollbarSlider-background); border-radius: 3px; }');
  lines.push('.message { padding: 10px 14px; line-height: 1.55; animation: fadeIn 0.15s ease; }');
  lines.push('@keyframes fadeIn { from { opacity: 0; transform: translateY(4px); } to { opacity: 1; transform: translateY(0); } }');
  lines.push('.message.user { background: var(--vscode-input-background); border-left: 2px solid var(--vscode-focusBorder); margin: 2px 8px; border-radius: 0 4px 4px 0; }');
  lines.push('.message.assistant { background: transparent; margin: 2px 0; }');
  lines.push('.message.error { background: var(--vscode-inputValidation-errorBackground); border: 1px solid var(--vscode-inputValidation-errorBorder); border-radius: 4px; margin: 4px 8px; color: var(--vscode-inputValidation-errorForeground); font-size: 12px; }');
  lines.push('.msg-label { font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 6px; opacity: 0.6; }');
  lines.push('.user .msg-label { color: var(--vscode-focusBorder); } .assistant .msg-label { color: var(--vscode-terminal-ansiGreen); }');
  lines.push('.msg-content { white-space: pre-wrap; word-break: break-word; }');
  lines.push('.code-block-wrapper { position: relative; margin: 8px 0; border-radius: 6px; overflow: hidden; border: 1px solid var(--vscode-panel-border); }');
  lines.push('.code-block-header { display: flex; align-items: center; justify-content: space-between; padding: 4px 10px; background: var(--vscode-editorGroupHeader-tabsBackground); font-size: 11px; color: var(--vscode-tab-inactiveForeground); }');
  lines.push('.code-block-header .lang { font-weight: 600; }');
  lines.push('.code-block-actions { display: flex; gap: 6px; }');
  lines.push('.code-btn { background: none; border: 1px solid var(--vscode-panel-border); color: var(--vscode-button-secondaryForeground); cursor: pointer; padding: 2px 8px; border-radius: 3px; font-size: 11px; }');
  lines.push('.code-btn:hover { background: var(--vscode-button-secondaryHoverBackground); }');
  lines.push('.code-block-wrapper pre { margin: 0; padding: 12px; overflow-x: auto; background: var(--vscode-editor-background); font-family: var(--vscode-editor-font-family, monospace); font-size: var(--vscode-editor-font-size, 13px); line-height: 1.5; }');
  lines.push('.code-block-wrapper code { color: var(--vscode-editor-foreground); }');
  lines.push('.msg-content code { background: var(--vscode-textBlockQuote-background); padding: 1px 5px; border-radius: 3px; font-family: var(--vscode-editor-font-family, monospace); font-size: 0.9em; }');
  lines.push('.cursor { display: inline-block; width: 2px; height: 1em; background: var(--vscode-terminal-foreground); vertical-align: text-bottom; animation: blink 0.8s step-end infinite; margin-left: 1px; }');
  lines.push('@keyframes blink { 50% { opacity: 0; } }');
  lines.push('#welcome { padding: 20px 16px; text-align: center; color: var(--vscode-descriptionForeground); display: flex; flex-direction: column; align-items: center; gap: 12px; }');
  lines.push('#welcome h2 { font-size: 14px; font-weight: 600; color: var(--vscode-foreground); } #welcome p { font-size: 12px; line-height: 1.5; }');
  lines.push('.welcome-tip { background: var(--vscode-textBlockQuote-background); border-left: 2px solid var(--vscode-focusBorder); padding: 8px 10px; border-radius: 0 4px 4px 0; text-align: left; font-size: 12px; width: 100%; }');
  lines.push('.welcome-tip strong { display: block; margin-bottom: 2px; color: var(--vscode-foreground); }');
  lines.push('#input-area { border-top: 1px solid var(--vscode-panel-border); padding: 10px; background: var(--vscode-sideBar-background); flex-shrink: 0; }');
  lines.push('#input-wrapper { display: flex; gap: 6px; align-items: flex-end; background: var(--vscode-input-background); border: 1px solid var(--vscode-input-border); border-radius: 6px; padding: 6px 8px; }');
  lines.push('#input-wrapper:focus-within { border-color: var(--vscode-focusBorder); }');
  lines.push('#user-input { flex: 1; background: none; border: none; color: var(--vscode-input-foreground); font-family: var(--vscode-font-family); font-size: var(--vscode-font-size); resize: none; outline: none; max-height: 120px; min-height: 20px; line-height: 1.4; overflow-y: auto; }');
  lines.push('#send-btn { background: var(--vscode-button-background); color: var(--vscode-button-foreground); border: none; border-radius: 4px; width: 28px; height: 28px; cursor: pointer; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }');
  lines.push('#send-btn:hover:not(:disabled) { background: var(--vscode-button-hoverBackground); } #send-btn:disabled { opacity: 0.4; cursor: not-allowed; }');
  lines.push('#stop-btn { background: none; border: 1px solid var(--vscode-panel-border); color: var(--vscode-button-secondaryForeground); border-radius: 4px; width: 28px; height: 28px; cursor: pointer; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }');
  lines.push('#stop-btn:hover:not(:disabled) { background: var(--vscode-button-secondaryHoverBackground); } #stop-btn:disabled { opacity: 0.4; cursor: not-allowed; }');
  lines.push('#status-bar { font-size: 10px; color: var(--vscode-descriptionForeground); padding: 4px 2px 0; min-height: 16px; }');
  lines.push('.status-thinking { color: var(--vscode-terminal-ansiYellow); } .status-done { color: var(--vscode-terminal-ansiGreen); }');
  lines.push('.status-stopped { color: var(--vscode-terminal-ansiRed); }');
  lines.push('#config-warning { margin: 8px; padding: 10px; background: var(--vscode-inputValidation-warningBackground); border: 1px solid var(--vscode-inputValidation-warningBorder); border-radius: 4px; font-size: 12px; display: none; }');
  lines.push('#config-warning a { color: var(--vscode-textLink-foreground); cursor: pointer; text-decoration: underline; }');
  lines.push('</style></head><body>');

  lines.push('<div id="header"><div id="header-title">');
  lines.push('<svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zm0 1a6 6 0 1 1 0 12A6 6 0 0 1 8 2zm-1 3v2H5v2h2v2h2V9h2V7H9V5H7z"/></svg>');
  lines.push('Azure Codex</div><div id="header-actions">');
  lines.push('<button class="icon-btn" id="context-btn" title="Toggle Context"><svg width="14" height="14" viewBox="0 0 16 16" fill="currentColor"><path d="M2 3.5A1.5 1.5 0 0 1 3.5 2h9A1.5 1.5 0 0 1 14 3.5v9A1.5 1.5 0 0 1 12.5 14h-9A1.5 1.5 0 0 1 2 12.5v-9zM3.5 3a.5.5 0 0 0-.5.5V6h10V3.5a.5.5 0 0 0-.5-.5h-9zM13 7H3v5.5a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5V7z"/></svg></button>');
  lines.push('<button class="icon-btn" id="attach-btn" title="Add Files / Images"><svg width="14" height="14" viewBox="0 0 16 16" fill="currentColor"><path d="M8 2a.75.75 0 0 1 .75.75V7.25H13.25a.75.75 0 0 1 0 1.5H8.75V13.25a.75.75 0 0 1-1.5 0V8.75H2.75a.75.75 0 0 1 0-1.5H7.25V2.75A.75.75 0 0 1 8 2z"/></svg></button>');
  lines.push('<button class="icon-btn" id="undo-btn" title="Undo last applied change" disabled><svg width="14" height="14" viewBox="0 0 16 16" fill="currentColor"><path d="M2.5 7.5a.75.75 0 0 1 .75-.75H9.5a4 4 0 1 1 0 8H8a.75.75 0 0 1 0-1.5h1.5a2.5 2.5 0 1 0 0-5H3.25A.75.75 0 0 1 2.5 7.5z"/><path d="M6.53 3.22a.75.75 0 0 1 0 1.06L4.31 6.5l2.22 2.22a.75.75 0 1 1-1.06 1.06l-2.75-2.75a.75.75 0 0 1 0-1.06l2.75-2.75a.75.75 0 0 1 1.06 0z"/></svg></button>');
  lines.push('<button class="icon-btn" id="settings-btn" title="Open Settings"><svg width="14" height="14" viewBox="0 0 16 16" fill="currentColor"><path d="M9.1 0L8 .9l-1 .5-1.1-.2L5.3 0l-.9.6-.8.7.1 1.1-.4 1-.9.5L2 4.5v1.1l1 .5.4 1-.1 1.1.8.7.9.6 1.1-.2 1 .4.9.5L8 11.1l1.1-.5 1 .4 1.1.2.9-.6.8-.7-.1-1.1.4-1 1-.5V4.5l-1-.6-.4-1 .1-1.1-.8-.7L9.1 0zM8 2.5a3.5 3.5 0 1 1 0 7 3.5 3.5 0 0 1 0-7z"/></svg></button>');
  lines.push('<button class="icon-btn" id="clear-btn" title="Clear Chat"><svg width="14" height="14" viewBox="0 0 16 16" fill="currentColor"><path d="M8 .9L1.5 4.4v7.2L8 15.1l6.5-3.5V4.4L8 .9zm0 1.2l5.5 3-5.5 3-5.5-3 5.5-3zm-6 3.8l5.5 3v5.8L2 11.1V5.9zm7 8.8V5.9l5.5-3v5.2L9 14.7z"/></svg></button>');
  lines.push('</div></div>');
  lines.push('<div id="config-warning">&#9888; Azure OpenAI is not configured. <a id="open-settings-link">Open Settings</a> to add your endpoint and API key.</div>');
  lines.push('<div id="context-drawer"><div id="context-title"><span>Context</span><span class="ctx-muted" id="ctx-summary"></span></div><div id="context-body"></div></div>');
  lines.push('<div id="messages"><div id="welcome">');
  lines.push('<svg width="40" height="40" viewBox="0 0 16 16" fill="var(--vscode-focusBorder)"><path d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zm0 1a6 6 0 1 1 0 12A6 6 0 0 1 8 2zm-1 3v2H5v2h2v2h2V9h2V7H9V5H7z"/></svg>');
  lines.push('<h2>Azure Codex Chat</h2>');
  lines.push('<p>Powered by GPT-5.2 Codex Max on Azure OpenAI. Ask me to write, explain, fix, or review code.</p>');
  lines.push('<div class="welcome-tip"><strong>&#128161; Right-click any code</strong>Select code in the editor and right-click: Explain, Fix, or Generate Code.</div>');
  lines.push('<div class="welcome-tip"><strong>&#9000; Quick shortcuts</strong>Press Enter to send &middot; Shift+Enter for new line</div>');
  lines.push('</div></div>');
  lines.push('<div id="input-area"><div id="input-wrapper">');
  lines.push('<textarea id="user-input" placeholder="Ask Azure Codex anything..." rows="1"></textarea>');
  lines.push('<button id="stop-btn" title="Stop" disabled><svg width="14" height="14" viewBox="0 0 16 16" fill="currentColor"><path d="M4 4.5A.5.5 0 0 1 4.5 4h7a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-.5.5h-7a.5.5 0 0 1-.5-.5v-7z"/></svg></button>');
  lines.push('<button id="send-btn" title="Send (Enter)"><svg width="14" height="14" viewBox="0 0 16 16" fill="currentColor"><path d="M.5 1.5l15 6.5-15 6.5V9.5l11-2.5L.5 4.5V1.5z"/></svg></button>');
  lines.push('</div><div id="status-bar"></div></div>');

  lines.push('<script>');
  lines.push('const vscode = acquireVsCodeApi();');
  lines.push('const messagesEl = document.getElementById("messages");');
  lines.push('const inputEl = document.getElementById("user-input");');
  lines.push('const sendBtn = document.getElementById("send-btn");');
  lines.push('const stopBtn = document.getElementById("stop-btn");');
  lines.push('const undoBtn = document.getElementById("undo-btn");');
  lines.push('const statusBar = document.getElementById("status-bar");');
  lines.push('const welcome = document.getElementById("welcome");');
  lines.push('const configWarning = document.getElementById("config-warning");');
  lines.push('const contextDrawer = document.getElementById("context-drawer");');
  lines.push('const contextBody = document.getElementById("context-body");');
  lines.push('const ctxSummary = document.getElementById("ctx-summary");');
  lines.push('let isStreaming = false, currentMsgEl = null, currentContentEl = null, rawBuffer = "";');
  lines.push('let lastContext = null;');
  lines.push('');
  lines.push('inputEl.addEventListener("input", () => { inputEl.style.height = "auto"; inputEl.style.height = Math.min(inputEl.scrollHeight, 120) + "px"; });');
  lines.push('inputEl.addEventListener("keydown", (e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); sendMessage(); } });');
  lines.push('sendBtn.addEventListener("click", sendMessage);');
  lines.push('stopBtn.addEventListener("click", () => { if (isStreaming) vscode.postMessage({ type: "stopGeneration" }); });');
  lines.push('undoBtn.addEventListener("click", () => { if (!undoBtn.disabled) vscode.postMessage({ type: "undoLastApply" }); });');
  lines.push('document.getElementById("clear-btn").addEventListener("click", () => vscode.postMessage({ type: "clearHistory" }));');
  lines.push('document.getElementById("settings-btn").addEventListener("click", () => vscode.postMessage({ type: "openSettings" }));');
  lines.push('document.getElementById("open-settings-link").addEventListener("click", () => vscode.postMessage({ type: "openSettings" }));');
  lines.push('document.getElementById("attach-btn").addEventListener("click", () => vscode.postMessage({ type: "pickAttachments" }));');
  lines.push('document.getElementById("context-btn").addEventListener("click", () => { contextDrawer.classList.toggle("open"); });');
  lines.push('');

  lines.push('function renderContext(status) {');
  lines.push('  lastContext = status;');
  lines.push('  const auto = status && status.auto ? status.auto : {};');
  lines.push('  const pinned = status && status.pinned ? status.pinned : { textFiles: [], images: [] };');
  lines.push('  const autoBits = [];');
  lines.push('  if (auto.includeFileList) autoBits.push("file list");');
  lines.push('  if (auto.includeRootDocs) autoBits.push("README/package");');
  lines.push('  if (auto.includeActiveFile) autoBits.push("active file");');
  lines.push('  const pinCount = (pinned.textFiles ? pinned.textFiles.length : 0) + (pinned.images ? pinned.images.length : 0);');
  lines.push('  ctxSummary.textContent = (autoBits.length ? ("auto: " + autoBits.join(", ")) : "auto: off") + " · pinned: " + pinCount;');
  lines.push('  contextBody.innerHTML = "";');
  lines.push('  const autoEl = document.createElement("div"); autoEl.className = "ctx-section";');
  lines.push('  autoEl.innerHTML = "<div class=\\"ctx-row\\"><div><div><strong>Auto context</strong></div><div class=\\"ctx-muted\\">Sent on every message</div></div>" +');
  lines.push('    "<div style=\\"display:flex;gap:6px\\">" +');
  lines.push('      "<button class=\\"mini-btn\\" id=\\"toggle-model\\">" + ("Model: " + (auto.chatModelMode || "smart")) + "</button>" +');
  lines.push('      "<button class=\\"mini-btn\\" id=\\"toggle-agent\\">" + (auto.agentEnabled ? "Agent: On" : "Agent: Off") + "</button>" +');
  lines.push('      "<button class=\\"mini-btn\\" id=\\"toggle-autocontinue\\">" + (auto.autoContinueOnTruncation ? "Auto-continue: On" : "Auto-continue: Off") + "</button>" +');
  lines.push('      "<button class=\\"mini-btn\\" id=\\"toggle-autoapply\\">" + (auto.autoApplyFileChanges ? "Auto-apply: On" : "Auto-apply: Off") + "</button>" +');
  lines.push('    "</div></div>" +');
  lines.push('    "<div class=\\"ctx-list\\">" +');
  lines.push('    "<div class=\\"ctx-item\\"><span>File list</span><span class=\\"ctx-muted\\">" + (auto.includeFileList ? (auto.fileCount || 0) + " files" : "off") + "</span></div>" +');
  lines.push('    "<div class=\\"ctx-item\\"><span>Root docs</span><span class=\\"ctx-muted\\">" + (auto.includeRootDocs ? "on" : "off") + "</span></div>" +');
  lines.push('    "<div class=\\"ctx-item\\"><span>Active file</span><span class=\\"ctx-muted\\">" + (auto.includeActiveFile ? (auto.activeFile || "on") : "off") + "</span></div>" +');
  lines.push('    "<div class=\\"ctx-item\\"><span>Auto-continue</span><span class=\\"ctx-muted\\">" + (auto.autoContinueOnTruncation ? "on" : "off") + "</span></div>" +');
  lines.push('    "<div class=\\"ctx-item\\"><span>Memory</span><span class=\\"ctx-muted\\">" + (auto.memoryEnabled ? "on" : "off") + "</span></div>" +');
  lines.push('    "</div>";');
  lines.push('  contextBody.appendChild(autoEl);');
  lines.push('  const toggle = document.getElementById("toggle-autoapply");');
  lines.push('  if (toggle) toggle.addEventListener("click", () => {');
  lines.push('    vscode.postMessage({ type: "setConfig", key: "autoApplyFileChanges", value: !auto.autoApplyFileChanges });');
  lines.push('  });');
  lines.push('  const agentBtn = document.getElementById("toggle-agent");');
  lines.push('  if (agentBtn) agentBtn.addEventListener("click", () => {');
  lines.push('    vscode.postMessage({ type: "setConfig", key: "agentEnabled", value: !auto.agentEnabled });');
  lines.push('  });');
  lines.push('  const acBtn = document.getElementById("toggle-autocontinue");');
  lines.push('  if (acBtn) acBtn.addEventListener("click", () => {');
  lines.push('    vscode.postMessage({ type: "setConfig", key: "autoContinueOnTruncation", value: !auto.autoContinueOnTruncation });');
  lines.push('  });');
  lines.push('  const modelBtn = document.getElementById("toggle-model");');
  lines.push('  if (modelBtn) modelBtn.addEventListener("click", () => {');
  lines.push('    const next = (String(auto.chatModelMode || "smart") === "fast") ? "smart" : "fast";');
  lines.push('    vscode.postMessage({ type: "setConfig", key: "chatModelMode", value: next });');
  lines.push('  });');
  lines.push('');
  lines.push('  const pinnedEl = document.createElement("div"); pinnedEl.className = "ctx-section";');
  lines.push('  pinnedEl.innerHTML = "<div class=\\"ctx-row\\"><div><div><strong>Pinned context</strong></div><div class=\\"ctx-muted\\">Added via + or Fetch</div></div></div>";');
  lines.push('  const list = document.createElement("div"); list.className = "ctx-list";');
  lines.push('  const addRow = (kind, label) => {');
  lines.push('    const row = document.createElement("div"); row.className = "ctx-item";');
  lines.push('    row.innerHTML = "<code>" + escHtml(label) + "</code><button class=\\"mini-btn\\">Remove</button>";');
  lines.push('    row.querySelector("button").addEventListener("click", () => vscode.postMessage({ type: "removeContextItem", kind, label }));');
  lines.push('    list.appendChild(row);');
  lines.push('  };');
  lines.push('  (pinned.textFiles || []).forEach((p) => addRow("text", p));');
  lines.push('  (pinned.images || []).forEach((p) => addRow("image", p));');
  lines.push('  if (!(pinned.textFiles || []).length && !(pinned.images || []).length) {');
  lines.push('    const empty = document.createElement("div"); empty.className = "ctx-muted"; empty.textContent = "No pinned items yet.";');
  lines.push('    list.appendChild(empty);');
  lines.push('  }');
  lines.push('  pinnedEl.appendChild(list);');
  lines.push('  contextBody.appendChild(pinnedEl);');
  lines.push('}');
  lines.push('');

  lines.push('function sendMessage() {');
  lines.push('  const text = inputEl.value.trim();');
  lines.push('  if (!text || isStreaming) return;');
  lines.push('  inputEl.value = ""; inputEl.style.height = "auto";');
  lines.push('  vscode.postMessage({ type: "userMessage", text });');
  lines.push('}');
  lines.push('');
  lines.push('function hideWelcome() { if (welcome) welcome.style.display = "none"; }');
  lines.push('');
  lines.push('function appendUserMessage(text) {');
  lines.push('  hideWelcome();');
  lines.push('  const el = document.createElement("div");');
  lines.push('  el.className = "message user";');
  lines.push('  el.innerHTML = "<div class=\\"msg-label\\">You</div><div class=\\"msg-content\\">" + escHtml(text) + "</div>";');
  lines.push('  messagesEl.appendChild(el); scrollToBottom();');
  lines.push('}');
  lines.push('');
  lines.push('function startAssistantMessage() {');
  lines.push('  hideWelcome(); isStreaming = true; sendBtn.disabled = true; rawBuffer = "";');
  lines.push('  stopBtn.disabled = false;');
  lines.push('  currentMsgEl = document.createElement("div"); currentMsgEl.className = "message assistant";');
  lines.push('  currentMsgEl.innerHTML = "<div class=\\"msg-label\\">Azure Codex</div>";');
  lines.push('  currentContentEl = document.createElement("div"); currentContentEl.className = "msg-content";');
  lines.push('  const cursor = document.createElement("span"); cursor.className = "cursor"; cursor.id = "streaming-cursor";');
  lines.push('  currentContentEl.appendChild(cursor); currentMsgEl.appendChild(currentContentEl); messagesEl.appendChild(currentMsgEl);');
  lines.push('  statusBar.innerHTML = "<span class=\\"status-thinking\\">Generating...</span>"; scrollToBottom();');
  lines.push('}');
  lines.push('');
  lines.push('function appendToken(token) { rawBuffer += token; renderBuffer(); scrollToBottom(); }');
  lines.push('');
  lines.push('function renderBuffer() {');
  lines.push('  const cursor = document.getElementById("streaming-cursor");');
  lines.push('  if (cursor) cursor.remove();');
  lines.push('  currentContentEl.innerHTML = markdownToHtml(rawBuffer);');
  lines.push('  const newCursor = document.createElement("span"); newCursor.className = "cursor"; newCursor.id = "streaming-cursor";');
  lines.push('  currentContentEl.appendChild(newCursor);');
  lines.push('}');
  lines.push('');
  lines.push('function finishAssistantMessage() {');
  lines.push('  isStreaming = false; sendBtn.disabled = false; stopBtn.disabled = true;');
  lines.push('  const cursor = document.getElementById("streaming-cursor"); if (cursor) cursor.remove();');
  lines.push('  if (currentContentEl) { currentContentEl.innerHTML = markdownToHtml(rawBuffer); addCodeBlockButtons(currentContentEl); }');
  lines.push('  statusBar.innerHTML = "<span class=\\"status-done\\">Done</span>";');
  lines.push('  setTimeout(() => { statusBar.innerHTML = ""; }, 2000); scrollToBottom();');
  lines.push('  currentMsgEl = null; currentContentEl = null;');
  lines.push('}');
  lines.push('');
  lines.push('function stopAssistantMessage() {');
  lines.push('  isStreaming = false; sendBtn.disabled = false; stopBtn.disabled = true;');
  lines.push('  const cursor = document.getElementById("streaming-cursor"); if (cursor) cursor.remove();');
  lines.push('  if (currentContentEl) { currentContentEl.innerHTML = markdownToHtml(rawBuffer); addCodeBlockButtons(currentContentEl); }');
  lines.push('  statusBar.innerHTML = "<span class=\\"status-stopped\\">Stopped</span>";');
  lines.push('  setTimeout(() => { statusBar.innerHTML = ""; }, 2000); scrollToBottom();');
  lines.push('  currentMsgEl = null; currentContentEl = null;');
  lines.push('}');
  lines.push('');
  lines.push('function showError(text) {');
  lines.push('  isStreaming = false; sendBtn.disabled = false; stopBtn.disabled = true;');
  lines.push('  if (currentMsgEl) currentMsgEl.remove();');
  lines.push('  const el = document.createElement("div"); el.className = "message error";');
  lines.push('  el.textContent = "Error: " + text; messagesEl.appendChild(el); statusBar.innerHTML = ""; scrollToBottom();');
  lines.push('}');
  lines.push('');
  lines.push('function addCodeBlockButtons(container) {');
  lines.push('  container.querySelectorAll(".code-block-wrapper").forEach(function(wrapper) {');
  lines.push('    const codeEl = wrapper.querySelector("code");');
  lines.push('    const code = codeEl ? codeEl.textContent : "";');
  lines.push('    const copyBtn = wrapper.querySelector(".copy-btn");');
  lines.push('    const insertBtn = wrapper.querySelector(".insert-btn");');
  lines.push('    const applyBtn = wrapper.querySelector(".apply-btn");');
  lines.push('    const fetchBtn = wrapper.querySelector(".fetch-btn");');
  lines.push('    if (copyBtn) copyBtn.addEventListener("click", function() {');
  lines.push('      navigator.clipboard.writeText(code).then(function() {');
  lines.push('        copyBtn.textContent = "Copied!"; setTimeout(function() { copyBtn.textContent = "Copy"; }, 1500);');
  lines.push('      });');
  lines.push('    });');
  lines.push('    if (insertBtn) insertBtn.addEventListener("click", function() { vscode.postMessage({ type: "copyToEditor", code }); });');
  lines.push('    if (applyBtn) applyBtn.addEventListener("click", function() {');
  lines.push('      var lang = applyBtn.getAttribute("data-lang") || "file";');
  lines.push('      vscode.postMessage({ type: "applyFileBlock", lang: lang, code: code });');
  lines.push('    });');
  lines.push('    if (fetchBtn) fetchBtn.addEventListener("click", function() { vscode.postMessage({ type: "fetchRequestedFiles", code: code }); });');
  lines.push('  });');
  lines.push('}');
  lines.push('');
  lines.push('function markdownToHtml(text) {');
  lines.push('  var FENCE = "```";');
  lines.push('  var parts = text.split(new RegExp("(" + FENCE + "(?:\\\\w*)\\\\n?[\\\\s\\\\S]*?" + FENCE + ")", "g"));');
  lines.push('  text = parts.map(function(part) {');
  lines.push('    if (part.indexOf(FENCE) === 0) {');
  lines.push('      var afterFence = part.slice(3);');
  lines.push('      var nl = afterFence.indexOf("\\n");');
  lines.push('      var lang = nl > -1 ? afterFence.slice(0, nl).trim() : "code";');
  lines.push('      var rest = nl > -1 ? afterFence.slice(nl + 1) : afterFence;');
  lines.push('      var lastFence = rest.lastIndexOf(FENCE);');
  lines.push('      var code = lastFence > -1 ? rest.slice(0, lastFence).trim() : rest.trim();');
  lines.push('      var l = (lang || "code").toLowerCase();');
  lines.push('      var applyBtn = (l === "file" || l === "delete" || l === "edit") ? (\'<button class="code-btn apply-btn" data-lang="\' + escHtml(l) + \'">Apply</button>\') : "";');
  lines.push('      var fetchBtn = (l === "request") ? (\'<button class="code-btn fetch-btn">Fetch</button>\') : "";');
  lines.push('      var isFileOp = (l === "file" || l === "delete");');
  lines.push('      var insertBtn = (!isFileOp && l !== "request") ? \'<button class="code-btn insert-btn">Insert</button>\' : "";');
  lines.push('      return \'<div class="code-block-wrapper"><div class="code-block-header"><span class="lang">\' + escHtml(lang || "code") + \'</span><div class="code-block-actions">\' + fetchBtn + applyBtn + insertBtn + \'<button class="code-btn copy-btn">Copy</button></div></div><pre><code>\' + escHtml(code) + \'</code></pre></div>\';');
  lines.push('    }');
  lines.push('    return part;');
  lines.push('  }).join("");');
  lines.push('  text = text.replace(/`([^`]+)`/g, "<code>$1</code>");');
  lines.push('  text = text.replace(/\\*\\*(.+?)\\*\\*/g, "<strong>$1</strong>");');
  lines.push('  text = text.replace(/\\*(.+?)\\*/g, "<em>$1</em>");');
  lines.push('  text = text.replace(/^### (.+)$/gm, "<h3 style=\\"font-size:13px;margin:8px 0 4px\\">$1</h3>");');
  lines.push('  text = text.replace(/^## (.+)$/gm, "<h2 style=\\"font-size:14px;margin:10px 0 4px\\">$1</h2>");');
  lines.push('  text = text.replace(/^# (.+)$/gm, "<h1 style=\\"font-size:15px;margin:12px 0 4px\\">$1</h1>");');
  lines.push('  text = text.replace(/^\\s*[-*] (.+)$/gm, "<li style=\\"margin-left:16px\\">$1</li>");');
  lines.push('  text = text.replace(/^\\d+\\. (.+)$/gm, "<li style=\\"margin-left:16px\\">$1</li>");');
  lines.push('  text = text.replace(/\\n/g, "<br>");');
  lines.push('  text = text.replace(/<pre>([\\s\\S]*?)<\\/pre>/g, function(m, inner) { return "<pre>" + inner.replace(/<br>/g, "\\n") + "</pre>"; });');
  lines.push('  return text;');
  lines.push('}');
  lines.push('');
  lines.push('function escHtml(str) {');
  lines.push('  return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");');
  lines.push('}');
  lines.push('');
  lines.push('function scrollToBottom() { messagesEl.scrollTop = messagesEl.scrollHeight; }');
  lines.push('');
  lines.push('window.addEventListener("message", function(event) {');
  lines.push('  var msg = event.data;');
  lines.push('  switch (msg.type) {');
  lines.push('    case "userMessage": appendUserMessage(msg.text); break;');
  lines.push('    case "commandMessage": appendUserMessage("(" + msg.label + ") " + msg.text.substring(0, 60) + (msg.text.length > 60 ? "..." : "")); break;');
  lines.push('    case "assistantStart": startAssistantMessage(); break;');
  lines.push('    case "assistantToken": appendToken(msg.token); break;');
  lines.push('    case "assistantDone": finishAssistantMessage(); break;');
  lines.push('    case "assistantStopped": stopAssistantMessage(); break;');
  lines.push('    case "error": showError(msg.text); if (msg.text.includes("not configured")) configWarning.style.display = "block"; break;');
  lines.push('    case "clearHistory": messagesEl.innerHTML = ""; messagesEl.appendChild(welcome); welcome.style.display = "flex"; rawBuffer = ""; break;');
  lines.push('    case "contextStatus": renderContext(msg.status); break;');
  lines.push('    case "undoStatus":');
  lines.push('      undoBtn.disabled = !(msg.status && msg.status.canUndo);');
  lines.push('      undoBtn.title = (msg.status && msg.status.label) ? ("Undo: " + msg.status.label) : "Undo last applied change";');
  lines.push('      break;');
  lines.push('  }');
  lines.push('});');
  lines.push('vscode.postMessage({ type: "getContextStatus" });');
  lines.push('inputEl.focus();');
  lines.push('<\/script></body></html>');

  return lines.join('\n');
}
